package com.am.stbus.presentation.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF686013)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF0E58B)
val onPrimaryContainerLight = Color(0xFF4F4800)
val secondaryLight = Color(0xFF635F41)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEAE3BD)
val onSecondaryContainerLight = Color(0xFF4B472B)
val tertiaryLight = Color(0xFF33618D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD0E4FF)
val onTertiaryContainerLight = Color(0xFF154974)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFCF9F9)
val onBackgroundLight = Color(0xFF1D1C14)
val surfaceLight = Color(0xFFE8E8E8)
val onSurfaceLight = Color(0xFF1D1C14)
val surfaceVariantLight = Color(0xFFE8E2D0)
val onSurfaceVariantLight = Color(0xFF49473A)
val outlineLight = Color(0xFF7B7768)
val outlineVariantLight = Color(0xFFCBC6B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF323127)
val inverseOnSurfaceLight = Color(0xFFF6F0E3)
val inversePrimaryLight = Color(0xFFD4C972)
val surfaceDimLight = Color(0xFFDFDACC)
val surfaceBrightLight = Color(0xFFFEF9EB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF9F3E5)
val surfaceContainerLight = Color(0xFFF3EEE0)
val surfaceContainerHighLight = Color(0xFFEDE8DA)
val surfaceContainerHighestLight = Color(0xFFE7E2D5)

val primaryLightMediumContrast = Color(0xFF3C3700)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF776E21)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF3A371C)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF726E4F)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF00385F)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF43709D)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFEF9EB)
val onBackgroundLightMediumContrast = Color(0xFF1D1C14)
val surfaceLightMediumContrast = Color(0xFFFEF9EB)
val onSurfaceLightMediumContrast = Color(0xFF12110A)
val surfaceVariantLightMediumContrast = Color(0xFFE8E2D0)
val onSurfaceVariantLightMediumContrast = Color(0xFF39362A)
val outlineLightMediumContrast = Color(0xFF555345)
val outlineVariantLightMediumContrast = Color(0xFF706D5E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF323127)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF6F0E3)
val inversePrimaryLightMediumContrast = Color(0xFFD4C972)
val surfaceDimLightMediumContrast = Color(0xFFCBC6B9)
val surfaceBrightLightMediumContrast = Color(0xFFFEF9EB)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF9F3E5)
val surfaceContainerLightMediumContrast = Color(0xFFEDE8DA)
val surfaceContainerHighLightMediumContrast = Color(0xFFE1DDCF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD6D1C4)

val primaryLightHighContrast = Color(0xFF312D00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF514A00)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF302D13)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF4E4A2E)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF002E4F)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF194C76)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFEF9EB)
val onBackgroundLightHighContrast = Color(0xFF1D1C14)
val surfaceLightHighContrast = Color(0xFFFEF9EB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE8E2D0)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2E2C20)
val outlineVariantLightHighContrast = Color(0xFF4C493C)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF323127)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFD4C972)
val surfaceDimLightHighContrast = Color(0xFFBDB9AC)
val surfaceBrightLightHighContrast = Color(0xFFFEF9EB)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF6F0E3)
val surfaceContainerLightHighContrast = Color(0xFFE7E2D5)
val surfaceContainerHighLightHighContrast = Color(0xFFD9D4C7)
val surfaceContainerHighestLightHighContrast = Color(0xFFCBC6B9)

val primaryDark = Color(0xFFD4C972)
val onPrimaryDark = Color(0xFF363100)
val primaryContainerDark = Color(0xFF4F4800)
val onPrimaryContainerDark = Color(0xFFF0E58B)
val secondaryDark = Color(0xFFCEC7A3)
val onSecondaryDark = Color(0xFF343117)
val secondaryContainerDark = Color(0xFF4B472B)
val onSecondaryContainerDark = Color(0xFFEAE3BD)
val tertiaryDark = Color(0xFF9ECAFC)
val onTertiaryDark = Color(0xFF003256)
val tertiaryContainerDark = Color(0xFF154974)
val onTertiaryContainerDark = Color(0xFFD0E4FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF15140C)
val onBackgroundDark = Color(0xFFE7E2D5)
val surfaceDark = Color(0xFF15140C)
val onSurfaceDark = Color(0xFFE7E2D5)
val surfaceVariantDark = Color(0xFF49473A)
val onSurfaceVariantDark = Color(0xFFCBC6B5)
val outlineDark = Color(0xFF959181)
val outlineVariantDark = Color(0xFF49473A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E2D5)
val inverseOnSurfaceDark = Color(0xFF323127)
val inversePrimaryDark = Color(0xFF686013)
val surfaceDimDark = Color(0xFF15140C)
val surfaceBrightDark = Color(0xFF3B3930)
val surfaceContainerLowestDark = Color(0xFF0F0E07)
val surfaceContainerLowDark = Color(0xFF1D1C14)
val surfaceContainerDark = Color(0xFF212017)
val surfaceContainerHighDark = Color(0xFF2C2A21)
val surfaceContainerHighestDark = Color(0xFF37352C)

val primaryDarkMediumContrast = Color(0xFFEADE85)
val onPrimaryDarkMediumContrast = Color(0xFF2A2600)
val primaryContainerDarkMediumContrast = Color(0xFF9C9242)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFE4DDB7)
val onSecondaryDarkMediumContrast = Color(0xFF29260D)
val secondaryContainerDarkMediumContrast = Color(0xFF979170)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC5DFFF)
val onTertiaryDarkMediumContrast = Color(0xFF002745)
val tertiaryContainerDarkMediumContrast = Color(0xFF6894C3)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF15140C)
val onBackgroundDarkMediumContrast = Color(0xFFE7E2D5)
val surfaceDarkMediumContrast = Color(0xFF15140C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF49473A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE2DCCA)
val outlineDarkMediumContrast = Color(0xFFB6B2A1)
val outlineVariantDarkMediumContrast = Color(0xFF949080)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE7E2D5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2C2A21)
val inversePrimaryDarkMediumContrast = Color(0xFF504900)
val surfaceDimDarkMediumContrast = Color(0xFF15140C)
val surfaceBrightDarkMediumContrast = Color(0xFF47453B)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF080703)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1F1E15)
val surfaceContainerDarkMediumContrast = Color(0xFF2A281F)
val surfaceContainerHighDarkMediumContrast = Color(0xFF34332A)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF403E34)

val primaryDarkHighContrast = Color(0xFFFEF297)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD0C56E)
val onPrimaryContainerDarkHighContrast = Color(0xFF0E0B00)
val secondaryDarkHighContrast = Color(0xFFF8F1CA)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFCAC39F)
val onSecondaryContainerDarkHighContrast = Color(0xFF0E0B00)
val tertiaryDarkHighContrast = Color(0xFFE8F1FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9AC6F8)
val onTertiaryContainerDarkHighContrast = Color(0xFF000C1A)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF15140C)
val onBackgroundDarkHighContrast = Color(0xFFE7E2D5)
val surfaceDarkHighContrast = Color(0xFF15140C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49473A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF6F0DD)
val outlineVariantDarkHighContrast = Color(0xFFC7C3B1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE7E2D5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF504900)
val surfaceDimDarkHighContrast = Color(0xFF15140C)
val surfaceBrightDarkHighContrast = Color(0xFF525046)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF212017)
val surfaceContainerDarkHighContrast = Color(0xFF323127)
val surfaceContainerHighDarkHighContrast = Color(0xFF3D3B32)
val surfaceContainerHighestDarkHighContrast = Color(0xFF49473D)















