name: Android Build

on:
  push:
    branches: [ marinantonio-ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    default:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download extra files
      run: ls

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
